name: Start Push-Workflow
run-name: ${{ github.actor }} is pushing his branch Selenium Guide
on: [push]
jobs:
  install_packages:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: production
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build Angular project
        run: npm run build
      # - name: Cypress run
      #   uses: cypress-io/github-action@v6
      #   with:
      #     build: npm run build
      #     start: npm start
      - name: run Selenium
        run: 'node src\e2e\test-homepage-load.js'